### PR TITLE
Single track loop and other things

### PR DESCRIPTION
**Pull request by mang1985**
Now the playlists dropdown will load correctly even if the extra sensor is not enabled.

### CODE REVIEW

**Comment by mang1985** [comment]
After completing the third feature and conducting testing, I discovered that these modifications have many interdependencies and cannot be separated. Therefore, I had to submit them all together.

**Review by KoljaWindeler — APPROVED** [review]
Nice, I'll test here now

**Comment by KoljaWindeler** [comment]
Hi Mang, i found a few issues but I'm not sure if it is easy to fix them:
1. my player had strangly named input select fields (purposly) before the update .. once I've updated they didn't work anymore
image

so I go to reconfigure just to check if the checkmarks are set .. they are .. so i hit submit and get
image
I guess due to the missing select entry here.

I can see that my old, manually created inputs are still there
image

but also understand that the new one's are actually selects
image

I guess there is no way to make the transition smoother for the user, or?

**Comment by mang1985** [comment]
Hi Kolja,

With these changes, new users can easily select the dropdowns they want to use by checking the corresponding checkboxes in the config flow. For existing users, they can delete the YAML files used to create the old input_select, choose dropdowns in the config flow, and then add the new select entities to the dashboard to replace the old input_select (we cannot modify users' dashboards directly).

Overall, the new configuration method is simpler, and all entities are controlled within the component, which is beneficial for users with multiple accounts. Of course, we can still find ways to allow existing users to continue using the old input_select (although this may be a bit challenging, I already have some ideas on how to approach this).

**Comment by mang1985** [comment]
image
@KoljaWindeler Did you manage to save the settings successfully in the end?Is this issue still ongoing?

**Comment by KoljaWindeler** [comment]
I had to select any other option but the first and then it worked .. so yes

**Comment by mang1985** [comment]
image
I attempted to reproduce this error, and the issue arises because in the old configuration, shuffle_mode was of type int, whereas the new requirement is string. In the config_flow, the dropdown did not have the corresponding option, so users who did not reselect encountered this error because the new value needs to be a string. I have addressed this issue by updating the component. After updating and restarting HA, the component will automatically convert old int value to the corresponding new string value and update the config entry. @KoljaWindeler

**Pull request merged**
